### ISSUE TITLE
'daos_server' insta-crashes, and the offending line of code shouldn't even compile

### ISSUE THREAD

**Issue by TheOtherDave** [daos-stack/daos#10]
Hi, I'm trying to track down what has got to be the oddest thing I've come across... If I run the 'daos_server' command, I immediately get this error:
`DAOS I/O server exited with error: exit status 1`
Tracing through the source code, error is generated on line 199 of daos/src/iosrv/init.c:
```
	rc = crt_init(server_group_id,
		      CRT_FLAG_BIT_SERVER | CRT_FLAG_BIT_LM_DISABLE);
	if (rc)
		D_GOTO(exit_mod_init, rc);
```
'rc' gets set to -1003 here instead of 0. Grepping through the daos source tree shows that the only place it's defined is in daos/src/client/event.c, which defines it like this:
`#define crt_init(a,b,c)			({0;})`

Notice anything strange? 'crt_init' takes _three_ arguments, not the two arguments that are provided at the call site. Furthermore, if I paste that macro into a test program and assign its result to an int, I observe two other interesting things (both of which seem obvious, but I wanted to confirm). 1) it evaluates to 0, not -1003, and 2) its value doesn't depend on its arguments.

How is this code even compiling (in fact, it won't compile if I copy/paste it into a different test program until I add a third argument), let alone giving the value of -1003?

**Comment by johannlombardi** [comment]
The crt_init() macro you found is only used for unit tests.
In fact, DAOS uses CaRT as the underlying RPC layer and crt_init() is defined here.
https://github.com/daos-stack/cart/blob/master/src/include/cart/api.h#L91
https://github.com/daos-stack/cart/blob/master/src/cart/crt_init.c#L182

As for the error codes, there are defined here:
https://github.com/daos-stack/cart/blob/master/src/include/gurt/errno.h#L62
1003 is DER_INVAL or invalid parameter.

Did you run the daos_server with orterun as specified in the quickstart guide?
https://github.com/daos-stack/daos/blob/master/doc/quickstart.md#running-daos

**Comment by TheOtherDave** [comment]
Ah, ok, thanks. I wonder why VS Code thought it was a macro? That's gotta just be an issue on my machine.

WRT orterun, I've tried it both with and without... no change as far as this error is concerned. Orterun itself generates an error (something about not being able to register memory), but the error message indicates that it can deal with it. I'll get my laptop out and edit this to add the exact error.

**Comment by TheOtherDave** [comment]
Ah, ok, thanks. I wonder why VS Code thought it was a macro? That's gotta just be an issue on my machine.

WRT orterun, I've tried it both with and without... no change as far as this error is concerned. Orterun itself generates this error:
`[user@myhost daos]$ orterun -np 1 --hostfile ~/daos-host --enable-recovery --report-uri ~/daos-uri daos_server
--------------------------------------------------------------------------
Failed to register memory region (MR):

Hostname: myhost
Address:  294cd000
Length:   4194304
Error:    Cannot allocate memory
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Open MPI has detected that there are UD-capable Verbs devices on your
system, but none of them were able to be setup properly.  This may
indicate a problem on this system.

You job will continue, but Open MPI will ignore the "ud" oob component
in this run.

Hostname: myhost
--------------------------------------------------------------------------
2018/06/29 17:35:56 DAOS I/O server exited with error: exit status 1
`
('~/daos-host' contains only the ip address of myhost)

**Comment by johannlombardi** [comment]
You should probably add "--mca oob tcp" to your orterun command line. Also, could you please advise whether you set the following env variables:
export CRT_PHY_ADDR_STR="ofi+sockets"
export OFI_INTERFACE=eth0

**Comment by TheOtherDave** [comment]
That fixed it on my laptop; I'll try it on the server next time I'm in the office. Thanks, and sorry about the false alarm. Don't know how I missed that when I was reading through the QuickStart guide.
