### ISSUE TITLE
daos_spdk thread does not respect first_core config value

### ISSUE THREAD

**Issue by christgau** [daos-stack/daos#1025]
Unlike the `daos_io_server` threads, the `daos_spdk` threads appears not to respect the value of the `first_core` variable from the server config.

I've configured `first_core` for the single target of my testbed to 20, but the `daos_spdk_0` thread has an affinity set to core 0 when the server is running. I have to manually change the affinity mask in order avoid interference with started MPI programs.

I'm using daos v0.6.

**Comment by johannlombardi** [comment]
Thanks for the report. Let me file a ticket in http://jira.hpdd.intel.com to get this fixed.
