### ISSUE TITLE
dfuse_hl can't mount 

### ISSUE THREAD

**Issue by minmingzhu** [daos-stack/daos#1258]
I pulled  the branch of  lxz/tse_fix  and successful build .  When I use the dfsue_hl command mount, it will fail.

command : 
dfuse_hl /home/minmingz/dfuse  -s -f -o default_permissions -p 7ff4b5b6-b361-4401-b38a-d1f33a769e8c -c 7ff4b5b6-b361-4401-b38a-d1f33a769e8c  -l 0 -d

failed info : 
"
Pool Connect...
DFS Pool = 7ff4b5b6-b361-4401-b38a-d1f33a769e8c
DFS SVCL = 0
DFS Container: 7ff4b5b6-b361-4401-b38a-d1f33a769e8c
Failed dfs mount (2)
"

**Comment by liuxuezhao** [comment]
track by https://jira.hpdd.intel.com/browse/DAOS-3520, close this one.
